---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_solo
  # require_chef_omnibus: latest # will install on each run
  require_chef_omnibus: 11.8.2

platforms:

- name: ubuntu-12.04
  run_list:
  - "recipe[apt]"

- name: ubuntu-10.04
  run_list:
  - "recipe[apt]"

- name: debian-7.2.0
  run_list:
  - "recipe[apt]"

- name: centos-6.5
  run_list:
  - "recipe[yum]"
  - "recipe[yum::epel]"

- name: centos-5.10
  run_list:
  - "recipe[yum]"
  - "recipe[yum::epel]"

# not going to try until
# https://jira.mongodb.org/browse/SERVER-7285 is closed
#- name: fedora-19
  #run_list:
  #- "recipe[yum]"

 #- name: fedora-20
  #run_list:
  #- "recipe[yum]"

# maybe again oneday
 #- name: freebsd-9.2
  #run_list:
  #- "recipe[yum]"

suites:
- name: default
  run_list:
  - "recipe[mongodb]"

- name: default_10gen
  run_list:
  - "recipe[mongodb::10gen_repo]"
  - "recipe[mongodb]"

- name: configserver
  run_list:
  - "recipe[mongodb::configserver]"

- name: mongos
  run_list:
  - "recipe[chef-solo-search]"
  - "recipe[mongodb::mongos]"
  attributes:
    mongodb:
      cluster_name: default
      config:
        configdb: my_configserver

- name: mms_agent
  run_list:
  - "recipe[mongodb::mms_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
  excludes:
    # bson_ext fails to install because build essentials is not installed
    - centos-6.5
    # runit is failing to install
    - centos-5.10

- name: mms_monitoring_agent
  run_list:
  - "recipe[mongodb::mms_monitoring_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        monitoring:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart script uses setuid which is not present in this version
    - ubuntu-10.04
    # Upstart is not present
    - debian-7.2.0
    # Package does not create the user
    - centos-5.10
    
- name: mms_backup_agent
  run_list:
  - "recipe[mongodb::mms_backup_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        backup:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart script uses setuid which is not present in this version
    - ubuntu-10.04
    # Upstart is not present
    - debian-7.2.0
    # Package does not create the user
    - centos-5.10
