---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  # To run test-kitchen for OS X, create a box for 10.9, and add it to vagrant. See for example,
  # https://github.com/timsutton/osx-vm-templates
  # https://github.com/opscode/bento/blob/master/packer/macosx-10.9.json
  - name: macosx-10.9
  - name: macosx-10.10

suites:
  - name: default
    run_list:
      - recipe[build-essential]
      - recipe[homebrew::default]
      - recipe[homebrew::cask]
      - recipe[homebrew::install_formulas]
      - recipe[homebrew::install_casks]
      - recipe[homebrew::install_taps]
    attributes:
      homebrew:
        formulas:
          - redis
        casks:
          - caffeine
        taps:
          - homebrew/homebrew-games
